### ISSUE TITLE
Can't get core-list to display after upgrade

### ISSUE THREAD

**Issue by olemartin** [Polymer/core-list#47]
After I upgraded from 0.4.2 this code stopped working. I have read documentation, and I think I have implemented it correctly.

Please help.

```
<link rel="import" href="../../bower_components/core-list/core-list.html">

<polymer-element name="new-player" attributes="tournamentId" vertical layout>

    <template>
        hello
        <core-list data="{{personas}}">
            <template>
                <div class="item {{ {selected: selected} | tokenList }}">
                    {{model.name}}
                </div>
            </template>
        </core-list>

    </template>
    <script>
        Polymer("new-player", {
            created: function() {
                this.personas = [{"name": "Ole"}, {"name": "Per"}];
            }
        });
    </script>
</polymer-element>
```

**Comment by JustinXinLiu** [comment]
Hi @kevinpschaaf, since the bug is already fixed in 5.2, I am not sure why your jsbin (http://jsfiddle.net/zg5k5wez/4/) sample still doesn't work if I remove all the `updateSize()` code? Am I missing something here? Thanks in adv.

**Comment by kevinpschaaf** [comment]
@JustinXinLiu Thanks, that pointed out a missing resize notification in `core-animated-pages` for the initially selected page.  Fixed in https://github.com/Polymer/core-animated-pages/commit/91434b14f3218378258f639897a89a0a2b913194.

**Comment by kevinpschaaf** [comment]
@gazialankus: For now, I've added a `console.warn` when the core-list is mis-sized: https://github.com/Polymer/core-list/blob/master/core-list.html#L663, which should be logged for this sort of user error.

**Comment by JustinXinLiu** [comment]
Thanks @kevinpschaaf. Work like a charm!
