### ISSUE TITLE
ScrollToItem near end of list doesn't display higher items

### ISSUE THREAD

**Issue by WrinklyNinja** [Polymer/core-list#49]
What seems to be happening is that the virtual item you choose to scroll to is rendered as the first real item. This is fine if you've got at least one view height away from the bottom of the list, but within one view height from the bottom, the selected item can't appear at the top of the page, and since it's the first real item, nothing appears above it.

I'm not sure I've explained it well, but I can replicate it on the `<core-list>` [demo page](https://www.polymer-project.org/components/core-list/demo.html): just enter the following into your console:

```
document.body.firstElementChild.shadowRoot.getElementById('list').scrollToItem(50000);
```

**Comment by Ortham** [comment]
Closing this as it's obsolete.
