### ISSUE TITLE
Are there any plans to make this compatible with Polymer 1.0?

### ISSUE THREAD

**Issue by richardkazuomiller** [Polymer/core-list#94]
i.e. make a paper or iron version of it.

**Comment by zdarovka** [comment]
+1

**Comment by tantona** [comment]
+1

**Comment by notwaldorf** [comment]
We are currently working on porting `iron-list` to Polymer 1.0. It's not fallen off the radar :) /cc @cdata

**Comment by richardkazuomiller** [comment]
That's great to hear. I just discovered https://github.com/PolymerElements/iron-elements which has `iron-list` under elements in progress. I'll follow that and the rest of the organization for updates.

Thanks to all the contributors for the hard work. Polymer is awesome.

**Comment by arodic** [comment]
+1

**Comment by indolering** [comment]
Please stop with the +1s, they are already working on it and throwing in +1 just adds to everyone's notification queue.  Subscribe to notifications if you want updates.

**Comment by indolering** [comment]
So I gave a timeline for a contract gig that relies on this component.  According to the ETA on the iron-elements site, iron-list is about a week overdue.  My job could quite literally be on the line if this isn't out in the next week or so.  Is there an alpha/beta of the new component out there?  Is there a new ETA on this?

**Comment by jjordan1775** [comment]
iron-list is now available.
Here is the url https://github.com/polymerelements/iron-list

**Comment by indolering** [comment]
Please close.

**Comment by notwaldorf** [comment]
Closing :)
